/**
 * Codex app-server method names we actually speak.
 * Source: packages/protocol/generated/ClientRequest.ts + ServerRequest.ts
 * Regenerated by `pnpm proto:gen` against CODEX_VERSION.
 */
export const ClientMethod = {
  initialize: "initialize",
  threadStart: "thread/start",
  threadResume: "thread/resume",
  turnStart: "turn/start",
  turnInterrupt: "turn/interrupt",
} as const;

export const ClientNotify = {
  initialized: "initialized",
} as const;

export const ServerMethod = {
  commandApproval: "item/commandExecution/requestApproval",
  fileChangeApproval: "item/fileChange/requestApproval",
  permissionsApproval: "item/permissions/requestApproval",
  requestUserInput: "item/tool/requestUserInput",
  toolCall: "item/tool/call",
  currentTime: "currentTime/read",
} as const;

export const ServerNotify = {
  error: "error",
  threadStarted: "thread/started",
  threadStatusChanged: "thread/status/changed",
  turnStarted: "turn/started",
  turnCompleted: "turn/completed",
  itemStarted: "item/started",
  itemCompleted: "item/completed",
} as const;

export const OptOutDeltas = [
  "item/agentMessage/delta",
  "item/reasoning/textDelta",
  "item/reasoning/summaryTextDelta",
  "item/commandExecution/outputDelta",
  "item/fileChange/outputDelta",
  "item/plan/delta",
] as const;

export const HostTool = {
  commitModel: "workspace_commit_model",
  generate3d: "workspace_generate_3d",
  runBlender: "workspace_run_blender",
  listAssets: "workspace_list_assets",
} as const;
