import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { repoRoot } from "./workspace.ts";

export type LabConfig = {
  apiKey: string;
  baseUrl: string;
  model: string;
  provider: string;
  blenderBin: string;
  approvalPolicy: "never" | "on-request";
  codexHome: string;
};

export function loadConfig(env: NodeJS.ProcessEnv = process.env): LabConfig {
  const repoHome = join(repoRoot, ".codex-home");
  return {
    apiKey: env.OPENAI_API_KEY ?? "",
    baseUrl: env.OPENAI_BASE_URL ?? "https://api.openai.com/v1",
    model: env.MODEL ?? "gpt-4o",
    provider: env.PROVIDER ?? "openai",
    blenderBin: env.BLENDER_BIN ?? "/Applications/Blender.app/Contents/MacOS/Blender",
    approvalPolicy: env.APPROVAL_POLICY === "on-request" ? "on-request" : "never",
    codexHome: env.CODEX_HOME && env.CODEX_HOME.length > 0 ? env.CODEX_HOME : repoHome,
  };
}

export function writeIsolatedCodexHome(cfg: LabConfig): void {
  mkdirSync(cfg.codexHome, { recursive: true });
  const toml = `# generated by desktop-3d-agent doctor/lab
model = "${cfg.model}"
model_provider = "${cfg.provider}"

[model_providers.${cfg.provider}]
name = "${cfg.provider}"
base_url = "${cfg.baseUrl}"
env_key = "OPENAI_API_KEY"
wire_api = "responses"
`;
  writeFileSync(join(cfg.codexHome, "config.toml"), toml);
  if (!existsSync(join(cfg.codexHome, "auth.json")) && cfg.apiKey) {
    // Codex CLI reads OPENAI_API_KEY from env; we do not write secrets to disk.
  }
}
